# Generated by Django 2.0 on 2018-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedIncomeQuantPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddatamodel',
            name='endTime',
            field=models.DateField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='loaddatamodel',
            name='startTime',
            field=models.DateField(null=True, verbose_name='开始时间'),
        ),
    ]
