# Generated by Django 2.0.1 on 2018-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionQuotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loadDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qixian', models.CharField(max_length=20, verbose_name='期权期限')),
                ('selected_date', models.CharField(max_length=20, verbose_name='报价日期')),
                ('instrument', models.CharField(max_length=50, verbose_name='标的')),
                ('futuresType', models.CharField(max_length=20, verbose_name='标的合约')),
                ('startTime', models.DateField(null=True, verbose_name='开始时间')),
                ('endTime', models.DateField(null=True, verbose_name='结束时间')),
                ('containerName', models.CharField(max_length=50, verbose_name='容器名')),
                ('forward', models.CharField(max_length=20, verbose_name='期货目标价格')),
                ('lastPrice', models.CharField(max_length=20, verbose_name='上日收盘价')),
                ('quoteData', models.TextField(default='--', verbose_name='期货序列数据')),
                ('TQuoteData', models.TextField(default='--', verbose_name='期货T型报价序列数据')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
