# Generated by Django 2.0 on 2018-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loadUserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='用户名')),
                ('userInfo', models.TextField(default='--', verbose_name='用户信息')),
            ],
        ),
    ]
