# Generated by Django 2.0 on 2018-03-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20180319_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaduserdatamodel',
            old_name='userData',
            new_name='data',
        ),
    ]
