# Generated by Django 2.0 on 2018-03-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_auto_20180322_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaduserdatamodel',
            old_name='data',
            new_name='userData',
        ),
    ]
